name: .NET Build/Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
     
    - name: Restore packages
      run: nuget restore NamedPipeWrapper.sln
    
    - name: Setup VS2019
      uses: warrenbuckley/Setup-MSBuild@v1
    
    - name: Build
      run: msbuild NamedPipeWrapper.sln
    
    - name: Test
      run: dotnet test --verbosity normal --logger:"nunit;LogFilePath=TestResults/test-result.xml"
        
    - uses: MirrorNG/nunit-reporter@v1.0.9
      if: always()
      with:
        path: "tests/**/TestResults/*.xml"
        access-token: ${{ secrets.GITHUB_TOKEN }}
